import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const openApiPath = path.join(rootDir, 'openapi.json');
const outputPath = path.join(rootDir, 'src', 'generated.ts');

export const createGeneratedSource = (spec) => `/* eslint-disable */
// This file is auto-generated by scripts/generate.mjs.
// Do not edit directly.
export const openApiSpec = ${JSON.stringify(spec, null, 2)} as const;
export type OpenApiSpec = typeof openApiSpec;
`;

const shouldRun = process.argv[1] === fileURLToPath(import.meta.url);
if (shouldRun) {
  const rawSpec = readFileSync(openApiPath, 'utf8');
  const spec = JSON.parse(rawSpec);
  const source = createGeneratedSource(spec);
  writeFileSync(outputPath, source);
  console.log(`Generated ${path.relative(rootDir, outputPath)}`);
}
