/* eslint-disable */
// This file is auto-generated by scripts/generate.mjs.
// Do not edit directly.
export const openApiSpec = {
  "openapi": "3.0.3",
  "info": {
    "title": "Comparison Prices API",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "https://api.example.com"
    }
  ],
  "paths": {
    "/stores": {
      "get": {
        "summary": "List available stores",
        "operationId": "listStores",
        "responses": {
          "200": {
            "description": "Stores list",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StoreListResponse"
                }
              }
            }
          }
        }
      }
    },
    "/search": {
      "get": {
        "summary": "Search products by query",
        "operationId": "searchProducts",
        "parameters": [
          {
            "name": "q",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "storeId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "minimum": 1,
              "maximum": 100,
              "default": 20
            }
          },
          {
            "name": "cursor",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product search results",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductSearchResponse"
                }
              }
            }
          }
        }
      }
    },
    "/list-totals": {
      "post": {
        "summary": "Calculate totals per store for a list",
        "operationId": "calculateListTotals",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ListTotalsRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "List totals per store",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ListTotalsResponse"
                }
              }
            }
          }
        }
      }
    },
    "/price-history": {
      "get": {
        "summary": "Fetch price history for a product",
        "operationId": "getPriceHistory",
        "parameters": [
          {
            "name": "productId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "storeId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Price history response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PriceHistoryResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Store": {
        "type": "object",
        "required": [
          "id",
          "name",
          "currency"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "logoUrl": {
            "type": "string",
            "nullable": true
          },
          "currency": {
            "type": "string",
            "example": "MXN"
          },
          "region": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "Product": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "brand": {
            "type": "string",
            "nullable": true
          },
          "sizeLabel": {
            "type": "string",
            "nullable": true
          },
          "imageUrl": {
            "type": "string",
            "nullable": true
          },
          "category": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "PriceSnapshot": {
        "type": "object",
        "required": [
          "storeId",
          "price",
          "capturedAt"
        ],
        "properties": {
          "storeId": {
            "type": "string"
          },
          "price": {
            "type": "number",
            "format": "float"
          },
          "capturedAt": {
            "type": "string",
            "format": "date-time"
          },
          "isPromo": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "ListItem": {
        "type": "object",
        "required": [
          "productId",
          "quantity"
        ],
        "properties": {
          "productId": {
            "type": "string"
          },
          "quantity": {
            "type": "number",
            "format": "float"
          },
          "unitLabel": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "StoreTotal": {
        "type": "object",
        "required": [
          "storeId",
          "total"
        ],
        "properties": {
          "storeId": {
            "type": "string"
          },
          "total": {
            "type": "number",
            "format": "float"
          },
          "savings": {
            "type": "number",
            "format": "float",
            "nullable": true
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          }
        }
      },
      "StoreListResponse": {
        "type": "object",
        "required": [
          "stores"
        ],
        "properties": {
          "stores": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Store"
            }
          }
        }
      },
      "ProductSearchResponse": {
        "type": "object",
        "required": [
          "products"
        ],
        "properties": {
          "products": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Product"
            }
          },
          "nextCursor": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "ListTotalsRequest": {
        "type": "object",
        "required": [
          "items"
        ],
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ListItem"
            }
          }
        }
      },
      "ListTotalsResponse": {
        "type": "object",
        "required": [
          "totals"
        ],
        "properties": {
          "totals": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/StoreTotal"
            }
          }
        }
      },
      "PriceHistoryPoint": {
        "type": "object",
        "required": [
          "capturedAt",
          "price"
        ],
        "properties": {
          "capturedAt": {
            "type": "string",
            "format": "date-time"
          },
          "price": {
            "type": "number",
            "format": "float"
          },
          "isPromo": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "PriceHistoryResponse": {
        "type": "object",
        "required": [
          "product",
          "history"
        ],
        "properties": {
          "product": {
            "$ref": "#/components/schemas/Product"
          },
          "history": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PriceHistoryPoint"
            }
          }
        }
      }
    }
  }
} as const;
export type OpenApiSpec = typeof openApiSpec;
